services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netengine\FalSecuredownload\:
    resource: '../Classes/*'

  Netengine\FalSecuredownload\Hooks\DocHeaderButtonsHook:
    public: true

  Netengine\FalSecuredownload\Controller\BePublicUrlController:
    public: true

  Netengine\FalSecuredownload\Controller\FileTreeController:
    public: true

  Netengine\FalSecuredownload\Hooks\CmsLayout:
    public: true

  Netengine\FalSecuredownload\Service\LeafStateService:
    public: true

  Netengine\FalSecuredownload\ContextMenu\ItemProvider:
    public: true
    arguments:
      $table: ''
      $identifier: ''
      $context: ''

  Netengine\FalSecuredownload\Middleware\FileTreeState:
    public: true

  Netengine\FalSecuredownload\EventListener\FolderChangedEventListener:
    tags:
      - name: event.listener
        method: 'preFolderMove'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderMovedEvent
      - name: event.listener
        method: 'postFolderMove'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderMovedEvent
      - name: event.listener
        method: 'preFolderDelete'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderDeletedEvent
      - name: event.listener
        method: 'postFolderDelete'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderDeletedEvent
      - name: event.listener
        method: 'preFolderRename'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderRenamedEvent
      - name: event.listener
        method: 'postFolderRename'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderRenamedEvent

  Netengine\FalSecuredownload\EventListener\ModifyIconForResourcePropertiesEventListener:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent

  Netengine\FalSecuredownload\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent
